# Generated by Django 4.0 on 2022-01-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_lib', '0003_album_album_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
